version: '3'

services:
  detect-cat:
    image: catdetector:v1
    build:
      context: ./src/detect_cat
    volumes:
      - ./data:/app/data
  tf-serving:
    image: tensorflow/serving
    environment:
        - MODEL_NAME=cat_classifier
        - MODEL_BASE_PATH=/models
    volumes:
        - ./models/cat_classifier/saved_model:/app/models/cat_classifier/1/
    ports:
        - 8500:8500
    restart: always